name: masjid_korea
description: "Aplikasi Masjid di Korea Selatan"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  equatable: ^2.0.7
  cloud_firestore: ^5.6.5
  url_launcher: ^6.3.1
  geolocator: ^13.0.2
  location: ^8.0.0
  flutter_bloc: ^9.1.0
  dio: ^5.8.0+1
  google_fonts: ^6.2.1
  firebase_core: ^3.12.1
  html: ^0.15.5
  web: ^1.1.1
  webview_flutter: ^4.10.0
  cached_network_image: ^3.4.1
  browser_launcher: ^1.1.3
  lottie: ^3.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_kmi.png"

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
